---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/3/19 6:00 PM
---

require("eclass")

local Cbase = class("base")

function Cbase:_init_(name)
    self.name = name
end

function Cbase:hello()
    return self.name
end

function Cbase:_del_()
    print("base del ... " .. self.name)
end

return Cbase
