---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/3/19 5:59 PM
---

require("eclass")
local Cone = require("one")

CThree = class("three", Cone)

function CThree:_init_(name)
    Cone._init_(self, name)
    self._child = Cone.new("child") -- new child.
end


function CThree:say()
    print("three start.")
    print("three say " .. self.name)
    print("child say.")
    self._child:say()
    print("three end.")
end

return CThree
