---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2023/3/19 5:58 PM
---

require("eclass")
local Cone = require("one")

CTwo = class("two", Cone)

function CTwo:_init_(name)
    Cone._init_(self, name)
end

function CTwo:say()
    print("two start")
    print("two say " .. self.name)
    print("call supper method.")
    Cone.say(self)
    print("two end\n")
end

return CTwo
