---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by liaozhaoyan.
--- DateTime: 2022/12/16 10:16 AM
---

local setmetatable = setmetatable
local getmetatable = getmetatable
local newproxy = newproxy

function class(name, super)
    local cls = {
        __super = super,
        __cname = name,
    }


    setmetatable(cls, {__index = super, })

    if not cls._init_ then
        cls._init_ = function(self, ...) end
    end

    if not cls._del_ then
        cls._del_ = function(self) end
    end

    cls.__meta = {__index = cls}
    cls.new = function(...)
        local obj = setmetatable({}, cls.__meta)
        obj:_init_(...)

        local proxy = newproxy(true)  -- create dummy userdata
        obj.__proxy = proxy  -- bind dummy userdata to object
        getmetatable(proxy).__gc = function()
            obj:_del_()
        end

        return obj
    end
    return cls
end
